variables:
  - group: aws-secrets

  # .net
  - name  : csharpProjectFiles
    value : '**/*.csproj'
  - name  : csharpTestProjectFiles
    value : 'test/**/*Tests.csproj'
  - name  : webAppProject
    value : "src/AwsOrleans.Host/AwsOrleans.Host.csproj"
  - name  : buildConfiguration
    value : 'Release'
  
  # NuGET
  - name  : nugetPackagesCachePath
    value : '$(Pipeline.Workspace)/.nuget/packages'
    
  # Service connections
  - name  : driftingBytesLabsAccount_ServiceConnectionName
    value : 'ADO Connector - Drifting Bytes Labs Account'
  
  # ECR
  - name  : imageRepository
    value : 'prototypes/aws-orleans'
  - name  : containerImagesFolder
    value : 'container_images'
  - name  : imageArtifactName
    value : 'aws-orleans'
  - name  : terraform_AwsRegion
    value : 'us-east-1'
  - name  : awsContainerRegistryUrl
    value : '696927138987.dkr.ecr.us-east-1.amazonaws.com'