variables:
  - template: ./build.yaml
    
  - name    : terraform_DevOpsFolder
    value   : '$(System.DefaultWorkingDirectory)/devops/terraform'
  - name    : terraformResourcesPath
    value   : '$(terraform_DevOpsFolder)/resources'
  - name    : deploy_ServiceName
    value   : 'aws-orleans'
  - name    : terraformContainer
    value   : '$(deploy_ServiceName)'